import type { Chapter } from "../../lib/policy-types";
import { ordinal } from "../../lib/policy-utils";

export function StructureEditor({ chapters, onChange }: { chapters: Chapter[]; onChange: (chapters: Chapter[]) => void }) {
  const addChapter = () => onChange([...chapters, { id: String(Date.now()), title: `第${ordinal(chapters.length + 1)}章`, articles: [] }]);
  const addArticle = (chapterIndex: number) => onChange(chapters.map((chapter, index) => index !== chapterIndex ? chapter : { ...chapter, articles: [...chapter.articles, { id: `${Date.now()}-${chapterIndex}`, title: `第${ordinal(chapter.articles.length + 1)}條`, text: "" }] }));
  // 章號由新增順序帶入預設值；可補上文字標題，例如「第一章　總則」。
  const updateChapterTitle = (chapterIndex: number, title: string) => onChange(chapters.map((chapter, index) => index !== chapterIndex ? chapter : { ...chapter, title }));
  const updateText = (chapterIndex: number, articleIndex: number, text: string) => onChange(chapters.map((chapter, index) => index !== chapterIndex ? chapter : { ...chapter, articles: chapter.articles.map((article, articlePosition) => articlePosition === articleIndex ? { ...article, text } : article) }));
  return <section className="structure-editor"><div className="structure-editor-head"><div><b>章節與條文</b><small>使用新增建立章節與條號；章節標題與條文內容可直接輸入。</small></div><button type="button" className="ghost" onClick={addChapter}>＋ 新增章節</button></div>{chapters.map((chapter, chapterIndex) => <div className="chapter-editor" key={chapter.id}><div className="chapter-title"><label>章節標題<input value={chapter.title} placeholder={`第${ordinal(chapterIndex + 1)}章　輸入標題`} onChange={(event) => updateChapterTitle(chapterIndex, event.target.value)} /></label><button type="button" onClick={() => addArticle(chapterIndex)}>＋ 新增條文</button></div>{chapter.articles.map((article, articleIndex) => <div className="article-editor" key={article.id}><b>{article.title}</b><textarea rows={3} value={article.text} placeholder="輸入條文內容" onChange={(event) => updateText(chapterIndex, articleIndex, event.target.value)} /><button type="button" className="remove-article" onClick={() => onChange(chapters.map((current, index) => index !== chapterIndex ? current : { ...current, articles: current.articles.filter((_, position) => position !== articleIndex) }))}>刪除</button></div>)}</div>)}{!chapters.length && <div className="empty">尚未建立條文。請先新增章節，再新增條文。</div>}</section>;
}
